# yaml file for creating StorageClass
#
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: default
parameters:
  ChargeType: PostPaid
  type: PTSSD
  zone: ""
provisioner: ebs.csi.volcengine.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
