apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: label-sync
  namespace: prow
spec:
  schedule: "17 * * * *"  # Every hour at 17 minutes past the hour
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: label-sync
    spec:
      template:
        spec:
          containers:
            - name: label-sync
              image: cr-cn-beijing.volces.com/bytedance-oss-prow/label_sync:v20211022-effa07f2d2
              imagePullPolicy: Always  # Good practice for dev/debugging, bad for prod
              args:
              - --config=/etc/config/labels.yaml
              # - --confirm=true
              - --orgs=kitex-contrib
              - --token=/etc/github/token
              volumeMounts:
              - name: oauth
                mountPath: /etc/github
                readOnly: true
              - name: config
                mountPath: /etc/config
                readOnly: true
          restartPolicy: Never
          volumes:
          - name: oauth
            secret:
              secretName: oauth-token
          - name: config
            configMap:
              name: label-config
