apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: peribolos
  namespace: prow
spec:
  schedule: "17 * * * *"  # Every hour at 17 minutes past the hour
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: peribolos
    spec:
      template:
        spec:
          containers:
          - name: peribolos
            image: cr-cn-beijing.volces.com/bytedance-oss-prow/peribolos:v20211022-effa07f2d2
            imagePullPolicy: Always  # Good practice for dev/debugging, bad for prod
            args:
            - --config-path=/etc/config/member.yaml
            - --github-token-path=/etc/github/token
            - --min-admins=2
            - --fix-org
            - --fix-org-members
            - --fix-teams
            - --fix-team-members
            # - --confirm=true
            volumeMounts:
            - name: oauth
              mountPath: /etc/github
              readOnly: true
            - name: test-config
              mountPath: /etc/config
              readOnly: true
          restartPolicy: Never
          volumes:
          - name: oauth
            secret:
              secretName: oauth-token
          - name: test-config
            configMap:
              name: member-config
